Repository aniketsen123/MVVM_notesapp, pull requests merged in 2023-02, with the labels that each got.

#7 app icon changed
  .idea/deploymentTargetDropDown.xml
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/notes_icon-playstore.png
  app/src/main/res/drawable/notes_icon_background.xml
  app/src/main/res/mipmap-anydpi-v26/notes_icon.xml
  app/src/main/res/mipmap-anydpi-v26/notes_icon_round.xml
  app/src/main/res/mipmap-hdpi/notes_icon.png
  app/src/main/res/mipmap-hdpi/notes_icon_foreground.png
  app/src/main/res/mipmap-hdpi/notes_icon_round.png
  app/src/main/res/mipmap-mdpi/notes_icon.png
  app/src/main/res/mipmap-mdpi/notes_icon_foreground.png
  app/src/main/res/mipmap-mdpi/notes_icon_round.png
  app/src/main/res/mipmap-xhdpi/notes_icon.png
  app/src/main/res/mipmap-xhdpi/notes_icon_foreground.png
  app/src/main/res/mipmap-xhdpi/notes_icon_round.png
  app/src/main/res/mipmap-xxhdpi/notes_icon.png
  app/src/main/res/mipmap-xxhdpi/notes_icon_foreground.png
  app/src/main/res/mipmap-xxhdpi/notes_icon_round.png
  app/src/main/res/mipmap-xxxhdpi/notes_icon.png
  app/src/main/res/mipmap-xxxhdpi/notes_icon_foreground.png
  app/src/main/res/mipmap-xxxhdpi/notes_icon_round.png
Labels: JWOC, Easy

#19 Updated UI
  app/build.gradle
  app/src/main/java/com/tec/mvvm_notesapp/Adapter/NotesAdapter.kt
  app/src/main/java/com/tec/mvvm_notesapp/add_note.kt
  app/src/main/java/com/tec/mvvm_notesapp/models/NoteViewModel.kt
  app/src/main/res/drawable/app_bg.jpg
  app/src/main/res/drawable/main_screen_bg.jpg
  app/src/main/res/layout/activity_add_note.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_splash_screen.xml
  app/src/main/res/menu/pop_up_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: JWOC, Medium

#20 Update README.md
  README.md
Labels: JWOC, Medium

#9 Dialog box added
  app/build.gradle
  app/src/main/java/com/tec/mvvm_notesapp/MainActivity.kt
Labels: JWOC, Medium

#27 Share Feature Done
  .idea/discord.xml
  app/src/main/java/com/tec/mvvm_notesapp/MainActivity.kt
  app/src/main/java/com/tec/mvvm_notesapp/add_note.kt
  app/src/main/res/drawable/share.xml
  app/src/main/res/layout/activity_add_note.xml
Labels: JWOC, Hard

#28 Update README.md
  README.md
Labels: JWOC, Easy

#29 Added subtitle box and solved dialog box bug
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/tec/mvvm_notesapp/Adapter/NotesAdapter.kt
  app/src/main/java/com/tec/mvvm_notesapp/Database/NoteDao.kt
  app/src/main/java/com/tec/mvvm_notesapp/Database/NotesRepository.kt
  app/src/main/java/com/tec/mvvm_notesapp/MainActivity.kt
  app/src/main/java/com/tec/mvvm_notesapp/add_note.kt
  app/src/main/java/com/tec/mvvm_notesapp/models/Notes.kt
  app/src/main/res/layout/activity_add_note.xml
  app/src/main/res/layout/list_item.xml
Labels: JWOC, Hard
